### ISSUE TITLE
Github set-output deprecation notice

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/version-bumper-action#34]
### What did you have in mind?

`set-output` is deprecated:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We use it for setting the parsed action output in [action.sh](https://github.com/TomerFi/version-bumper-action/blob/master/action.sh).

### Are you trying to fix a problem?

Prepare for deprecation by GitHub.

### Any lead on how this feature may be implemented?

Using [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).

**Comment by g4m3r0** [comment]
I would like to work on this issue. Kindly assign me to it :).

**Comment by TomerFi** [comment]
Thank you!

**Comment by TomerFi** [comment]
For reference, an [example of using GITHUB_OUTPUT environment file](
https://github.com/TomerFi/version-bumper/pull/96/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R62).

**Comment by g4m3r0** [comment]
I've just committed my changes, but I'm not really able to test the action myself. Can you take a look at it and might test if everything works fine as well?

In your example, the $GITHUB_OUTPUT variable is inside quotation marks but I think this is not necessary according to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and https://github.com/orgs/community/discussions/36617 . If you prefer putting it inside quotation marks then please let me know and I'll change it.
